import os
import logging
from typing import Optional, Dict

try:
    from substack import Api
    from substack.post import Post
    SUBSTACK_AVAILABLE = True
except ImportError:
    Api = None
    Post = None
    SUBSTACK_AVAILABLE = False
    logging.warning("substack package not installed — Substack publishing disabled")


class SubstackService:
    def __init__(self):
        """Initialize Substack service for automated publishing"""
        self.email = os.environ.get('SUBSTACK_EMAIL')
        self.password = os.environ.get('SUBSTACK_PASSWORD')
        self.publication_url = os.environ.get('SUBSTACK_PUBLICATION_URL')
        
        if not SUBSTACK_AVAILABLE:
            logging.warning("Substack SDK not installed — service disabled")
            return
        if not all([self.email, self.password, self.publication_url]):
            raise ValueError("SUBSTACK_EMAIL, SUBSTACK_PASSWORD, and SUBSTACK_PUBLICATION_URL environment variables are required")
        
        # Initialize the API connection
        self.api = None
        self.user_id = None
        
        logging.info("Substack service initialized successfully")

    def _initialize_api(self) -> bool:
        """Initialize Substack API connection"""
        try:
            if not self.api:
                self.api = Api(
                    email=self.email,
                    password=self.password,
                    publication_url=self.publication_url
                )
                self.user_id = self.api.get_user_id()
                logging.info(f"Substack API initialized with user ID: {self.user_id}")
            return True
        except Exception as e:
            logging.error(f"Failed to initialize Substack API: {e}")
            return False

    def publish_to_substack(self, title: str, body_markdown: str, image_path: str = None) -> Optional[str]:
        """
        Publish article to Substack following the specified format
        
        Args:
            title: Article title
            body_markdown: Article content in markdown format
            image_path: Optional path or URL to header image
            
        Returns:
            Published post URL if successful, None if failed
        """
        try:
            if not self._initialize_api():
                return None

            # Create the post
            post = Post(
                title=title,
                subtitle="Generated by Protocol Pulse AI",
                user_id=self.user_id
            )

            # Add body as paragraph (convert Markdown to Substack blocks if needed; simple for now)
            post.add({"type": "paragraph", "content": body_markdown})

            # Optional header image (from DALL-E path/URL)
            if image_path:
                try:
                    uploaded = self.api.get_image(image_path)  # Handles upload
                    if uploaded and uploaded.get("url"):
                        post.add({"type": "captionedImage", "src": uploaded.get("url")})
                        logging.info(f"Added header image to Substack post: {uploaded.get('url')}")
                except Exception as e:
                    logging.warning(f"Failed to upload image to Substack: {e}")
                    # Continue without image

            # Create draft
            draft = self.api.post_draft(post.get_draft())
            draft_id = draft.get("id")
            
            if not draft_id:
                logging.error("Failed to create Substack draft")
                return None

            logging.info(f"Created Substack draft with ID: {draft_id}")

            # Prepare for publishing
            self.api.prepublish_draft(draft_id)
            
            # Publish the draft
            published = self.api.publish_draft(draft_id)
            post_url = published.get("canonical_url")
            
            if post_url:
                logging.info(f"Successfully published to Substack: {post_url}")
                return post_url
            else:
                logging.error("Published to Substack but no URL returned")
                return None

        except Exception as e:
            logging.error(f"Substack publishing error: {e}")
            return None

    def publish_bitcoin_news(self, title: str, content: str, image_url: str = None) -> Optional[str]:
        """Publish Bitcoin news article to Substack"""
        try:
            # Format content for Substack newsletter
            formatted_title = f"🪙 {title}"
            
            # Add Protocol Pulse branding and Bitcoin focus
            newsletter_content = f"""
{content}

---

*This article was generated by Protocol Pulse AI - Your source for Bitcoin and DeFi analysis.*

*Subscribe for daily Bitcoin insights and DeFi protocol updates.*
"""
            
            return self.publish_to_substack(formatted_title, newsletter_content, image_url)
            
        except Exception as e:
            logging.error(f"Error publishing Bitcoin news to Substack: {e}")
            return None

    def publish_defi_analysis(self, title: str, content: str, image_url: str = None) -> Optional[str]:
        """Publish DeFi analysis article to Substack"""
        try:
            # Format content for DeFi analysis
            formatted_title = f"🏦 {title}"
            
            newsletter_content = f"""
{content}

---

*This DeFi analysis was generated by Protocol Pulse AI - Your trusted source for decentralized finance insights.*

*Stay ahead of DeFi trends with our daily protocol analysis.*
"""
            
            return self.publish_to_substack(formatted_title, newsletter_content, image_url)
            
        except Exception as e:
            logging.error(f"Error publishing DeFi analysis to Substack: {e}")
            return None

    def publish_market_update(self, title: str, content: str, image_url: str = None) -> Optional[str]:
        """Publish market update to Substack"""
        try:
            formatted_title = f"📈 {title}"
            
            newsletter_content = f"""
{content}

---

*Market updates powered by Protocol Pulse AI - Real-time Bitcoin and DeFi market analysis.*

*Get instant alerts on market movements and protocol updates.*
"""
            
            return self.publish_to_substack(formatted_title, newsletter_content, image_url)
            
        except Exception as e:
            logging.error(f"Error publishing market update to Substack: {e}")
            return None

    def create_draft_only(self, title: str, body_markdown: str, image_path: str = None) -> Optional[str]:
        """Create a draft without publishing for review"""
        try:
            if not self._initialize_api():
                return None

            post = Post(
                title=title,
                subtitle="Generated by Protocol Pulse AI - DRAFT",
                user_id=self.user_id
            )

            post.add({"type": "paragraph", "content": body_markdown})

            if image_path:
                try:
                    uploaded = self.api.get_image(image_path)
                    if uploaded and uploaded.get("url"):
                        post.add({"type": "captionedImage", "src": uploaded.get("url")})
                except Exception as e:
                    logging.warning(f"Failed to upload image to draft: {e}")

            draft = self.api.post_draft(post.get_draft())
            draft_id = draft.get("id")
            
            if draft_id:
                logging.info(f"Created Substack draft for review: {draft_id}")
                return draft_id
            else:
                logging.error("Failed to create Substack draft")
                return None

        except Exception as e:
            logging.error(f"Error creating Substack draft: {e}")
            return None

    def get_publication_stats(self) -> Dict:
        """Get publication statistics"""
        try:
            if not self._initialize_api():
                return {}

            # Note: python-substack library may have limited stats functionality
            # This is a placeholder for potential stats retrieval
            stats = {
                "publication_url": self.publication_url,
                "status": "connected",
                "user_id": self.user_id
            }
            
            return stats
            
        except Exception as e:
            logging.error(f"Error getting publication stats: {e}")
            return {"status": "error", "error": str(e)}

    def test_connection(self) -> bool:
        """Test Substack connection"""
        try:
            return self._initialize_api()
        except Exception as e:
            logging.error(f"Substack connection test failed: {e}")
            return False

    def format_content_for_newsletter(self, content: str, content_type: str = "article") -> str:
        """Format content specifically for newsletter consumption"""
        # Remove markdown formatting that doesn't work well in Substack
        formatted = content.replace('###', '').replace('##', '').replace('#', '')
        formatted = formatted.replace('**', '').replace('*', '')
        
        # Add newsletter-specific formatting
        if content_type == "bitcoin":
            header = "🪙 BITCOIN UPDATE\n\n"
        elif content_type == "defi":
            header = "🏦 DEFI ANALYSIS\n\n"
        else:
            header = "📰 PROTOCOL PULSE\n\n"
            
        footer = f"""

---

💡 What did you think of this analysis? Reply and let us know!

🔔 Never miss an update - make sure you're subscribed to Protocol Pulse

📈 Follow us for real-time Bitcoin and DeFi insights

---

*Powered by Protocol Pulse AI - The future of crypto journalism*
"""
        
        return header + formatted + footer

# Initialize the service (lazy — won't crash without substack package)
try:
    substack_service = SubstackService()
except Exception as e:
    logging.warning(f"SubstackService init failed: {e}")
    substack_service = None