#!/usr/bin/env python3
"""Transcript Intelligence — Extract KOL sentiment and themes from video transcripts.

Reads the 296+ YouTube transcripts generated by the video pipeline's channel scanner,
uses Claude to extract structured intelligence: sentiment, key quotes, themes,
price predictions. Feeds into sovereign context, morning brief, and /media KOL INTEL.

Usage:
    python3 services/transcript_intelligence.py                # Process latest (24h)
    python3 services/transcript_intelligence.py --hours 72     # Process last 72h
    python3 services/transcript_intelligence.py --all          # Process all transcripts
    python3 services/transcript_intelligence.py --digest       # Build digest only

Cron:
    0 */4 * * * cd ~/protocol_pulse && python3 services/transcript_intelligence.py
"""
import argparse
import json
import logging
import os
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("transcript_intelligence")

# ── Local LLM (Ollama/Gemma) — use first, fall back to Haiku ─────────────
try:
    from services.local_llm import (
        extract_kol_sentiment as _local_extract,
        summarize_creator_consensus as _local_summarize,
        is_available as local_llm_available,
    )
except ImportError:
    local_llm_available = lambda: False

# ── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
TRANSCRIPTS_DIR = BASE_DIR / "video_pipeline_v3" / "transcripts"
DATA_DIR = BASE_DIR / "data"
INTEL_DIR = DATA_DIR / "intelligence"
KOL_INTEL_PATH = INTEL_DIR / "kol_transcript_intel.json"
KOL_DIGEST_PATH = INTEL_DIR / "kol_transcript_digest.json"
PROCESSED_LOG = INTEL_DIR / "kol_processed.json"

# Ensure dirs exist
INTEL_DIR.mkdir(parents=True, exist_ok=True)


def _get_anthropic_client():
    """Lazy-load Anthropic client."""
    try:
        import anthropic
        api_key = os.environ.get("ANTHROPIC_API_KEY", "")
        if not api_key:
            # Try relay
            sys.path.insert(0, str(BASE_DIR / "video_pipeline_v3"))
            from relay import get_key
            api_key = get_key("ANTHROPIC_API_KEY")
        if not api_key:
            logger.error("ANTHROPIC_API_KEY not found")
            return None
        return anthropic.Anthropic(api_key=api_key)
    except ImportError:
        logger.error("anthropic package not installed")
        return None


def _load_processed_ids() -> set:
    """Load set of already-processed video IDs."""
    if PROCESSED_LOG.exists():
        try:
            data = json.loads(PROCESSED_LOG.read_text())
            return set(data.get("processed", []))
        except Exception:
            return set()
    return set()


def _save_processed_ids(ids: set):
    """Save processed video IDs."""
    PROCESSED_LOG.write_text(json.dumps({
        "processed": list(ids),
        "last_updated": datetime.now(timezone.utc).isoformat(),
        "count": len(ids),
    }, indent=2))


def load_transcripts(hours: int = 24, process_all: bool = False) -> List[dict]:
    """Load transcript JSON files, optionally filtered by recency.

    Args:
        hours: Only load transcripts modified within this many hours.
        process_all: Ignore hours filter, load everything.

    Returns:
        List of transcript dicts with: text, channel, title, video_id, duration.
    """
    if not TRANSCRIPTS_DIR.exists():
        logger.warning(f"Transcripts directory not found: {TRANSCRIPTS_DIR}")
        return []

    processed = _load_processed_ids()
    cutoff = time.time() - (hours * 3600)
    transcripts = []

    for tf in sorted(TRANSCRIPTS_DIR.glob("*.json"), key=os.path.getmtime, reverse=True):
        if not process_all and os.path.getmtime(tf) < cutoff:
            continue

        vid = tf.stem
        if vid in processed and not process_all:
            continue

        try:
            data = json.loads(tf.read_text())
            text = data.get("text", "")
            if not text or len(text) < 100:
                continue

            transcripts.append({
                "video_id": vid,
                "channel": data.get("channel", "Unknown"),
                "title": data.get("title", ""),
                "text": text[:8000],  # Truncate for API limits
                "duration": data.get("duration", 0),
                "file_mtime": os.path.getmtime(tf),
            })
        except Exception as e:
            logger.warning(f"Failed to load {tf.name}: {e}")

    logger.info(f"Loaded {len(transcripts)} transcripts (hours={hours}, all={process_all})")
    return transcripts


# ── Claude-powered Analysis ──────────────────────────────────────────────────

def extract_kol_sentiment(transcript: dict) -> Optional[dict]:
    """Extract structured KOL intelligence from a single transcript.

    Returns:
        dict with: channel, title, video_id, sentiment, sentiment_score,
                   main_thesis, key_quotes, topics, price_predictions,
                   confidence, analyzed_at
    """
    text = transcript["text"][:6000]
    channel = transcript.get("channel", "Unknown")
    title = transcript.get("title", "")

    # ── Try local LLM first (Gemma via Ollama — $0 cost) ──
    if local_llm_available():
        local_result = _local_extract(channel, text)
        if local_result:
            local_result.update({
                "channel": channel,
                "title": title,
                "video_id": transcript["video_id"],
                "duration": transcript.get("duration", 0),
                "analyzed_at": datetime.now(timezone.utc).isoformat(),
                "inference_source": "local_gemma",
            })
            logger.info(f"  {channel}: {local_result['sentiment']} ({local_result.get('sentiment_score', '?')}/100) [LOCAL]")
            return local_result
        logger.warning(f"  Local LLM failed for {channel}, falling back to Haiku")

    # ── Fallback: Claude Haiku API ──
    client = _get_anthropic_client()
    if not client:
        return None

    prompt = f"""Analyze this Bitcoin video transcript from {channel}: "{title}"

TRANSCRIPT (truncated):
{text}

Extract the following as JSON:
{{
  "sentiment": "bullish" | "bearish" | "neutral" | "mixed",
  "sentiment_score": 0-100 (0=extremely bearish, 50=neutral, 100=extremely bullish),
  "main_thesis": "1-2 sentence summary of the creator's main argument",
  "key_quotes": ["up to 3 notable direct quotes, max 100 chars each"],
  "topics": ["list of 3-5 specific topics discussed: e.g. 'ETF flows', 'mining difficulty', 'Fed policy'"],
  "price_prediction": "any specific price target or timeline mentioned, or null",
  "confidence": "high" | "medium" | "low" (how confident the creator seems)
}}

Focus on Bitcoin-specific content. Ignore ads, intros, sponsor segments.
Return ONLY the JSON object."""

    try:
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = resp.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1]
            if raw.endswith("```"):
                raw = raw[:-3]

        result = json.loads(raw)
        result.update({
            "channel": channel,
            "title": title,
            "video_id": transcript["video_id"],
            "duration": transcript.get("duration", 0),
            "analyzed_at": datetime.now(timezone.utc).isoformat(),
        })
        logger.info(f"  {channel}: {result['sentiment']} ({result['sentiment_score']}/100)")
        return result

    except Exception as e:
        logger.error(f"Analysis failed for {channel}/{transcript['video_id']}: {e}")
        return None


def extract_narrative_themes(analyses: List[dict]) -> List[dict]:
    """Identify trending topics across all creator analyses.

    Returns list of themes with:
        topic, creator_count, creators, avg_sentiment_score, example_quote
    """
    if not analyses:
        return []

    # Aggregate topics
    topic_map = {}
    for a in analyses:
        for topic in a.get("topics", []):
            topic_lower = topic.lower().strip()
            if topic_lower not in topic_map:
                topic_map[topic_lower] = {
                    "topic": topic,
                    "creators": [],
                    "scores": [],
                    "quotes": [],
                }
            entry = topic_map[topic_lower]
            channel = a.get("channel", "Unknown")
            if channel not in entry["creators"]:
                entry["creators"].append(channel)
            entry["scores"].append(a.get("sentiment_score", 50))
            for q in a.get("key_quotes", [])[:1]:
                if q not in entry["quotes"]:
                    entry["quotes"].append(q)

    # Sort by creator count (most discussed first)
    themes = []
    for key, data in sorted(topic_map.items(), key=lambda x: len(x[1]["creators"]), reverse=True):
        themes.append({
            "topic": data["topic"],
            "creator_count": len(data["creators"]),
            "creators": data["creators"][:5],
            "avg_sentiment_score": round(sum(data["scores"]) / len(data["scores"]), 1),
            "example_quote": data["quotes"][0] if data["quotes"] else None,
        })

    return themes[:15]  # Top 15 themes


def build_transcript_digest(hours: int = 24) -> dict:
    """Build a narrative digest summarizing what creators are saying.

    Feeds into morning brief (Satomi) and sovereign context.
    """
    # Load existing analyses
    if not KOL_INTEL_PATH.exists():
        return {"error": "No KOL intel data yet — run analysis first"}

    data = json.loads(KOL_INTEL_PATH.read_text())
    analyses = data.get("analyses", [])

    # Filter by time
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
    recent = [a for a in analyses if a.get("analyzed_at", "") >= cutoff]

    if not recent:
        return {"period_hours": hours, "creator_count": 0, "summary": "No recent analyses"}

    # Aggregate sentiment
    scores = [a["sentiment_score"] for a in recent if "sentiment_score" in a]
    sentiments = [a["sentiment"] for a in recent if "sentiment" in a]

    bullish_count = sentiments.count("bullish")
    bearish_count = sentiments.count("bearish")
    neutral_count = sentiments.count("neutral") + sentiments.count("mixed")

    # Extract themes
    themes = extract_narrative_themes(recent)

    # Build AI digest — local LLM first, Claude Haiku fallback
    summary = ""
    if recent:
        creator_summaries = "\n".join(
            f"- {a['channel']}: {a.get('main_thesis', 'N/A')} (sentiment: {a['sentiment']}, {a['sentiment_score']}/100)"
            for a in recent[:10]
        )
        # Try local LLM first
        if local_llm_available():
            summary = _local_summarize(creator_summaries)
            if summary:
                logger.info("Digest summary generated via local LLM")

        # Fallback to Haiku if local failed
        if not summary:
            client = _get_anthropic_client()
            if client:
                try:
                    resp = client.messages.create(
                        model="claude-haiku-4-5-20251001",
                        max_tokens=500,
                        messages=[{"role": "user", "content":
                            f"Summarize what Bitcoin creators are saying in 3-4 sentences. "
                            f"Focus on consensus and divergence:\n\n{creator_summaries}"}],
                    )
                    summary = resp.content[0].text.strip()
                except Exception as e:
                    logger.warning(f"Digest summary failed: {e}")

    digest = {
        "period_hours": hours,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "creator_count": len(recent),
        "avg_sentiment_score": round(sum(scores) / len(scores), 1) if scores else 50,
        "sentiment_breakdown": {
            "bullish": bullish_count,
            "bearish": bearish_count,
            "neutral": neutral_count,
        },
        "dominant_sentiment": max(
            [("bullish", bullish_count), ("bearish", bearish_count), ("neutral", neutral_count)],
            key=lambda x: x[1]
        )[0],
        "trending_themes": themes[:5],
        "summary": summary,
        "top_creators": [
            {"channel": a["channel"], "sentiment": a["sentiment"],
             "score": a["sentiment_score"], "thesis": a.get("main_thesis", "")}
            for a in recent[:5]
        ],
    }

    # Save digest
    KOL_DIGEST_PATH.write_text(json.dumps(digest, indent=2))
    logger.info(f"Digest built: {len(recent)} creators, avg score {digest['avg_sentiment_score']}")
    return digest


# ── Sovereign Context Integration ────────────────────────────────────────────

def update_kol_intel() -> dict:
    """Read latest transcripts, analyze them, update KOL intel cache.

    This is the main entry point called by cron.
    Returns: summary dict.
    """
    # Load new transcripts (last 24h, unprocessed)
    transcripts = load_transcripts(hours=24)
    if not transcripts:
        logger.info("No new transcripts to process")
        return {"processed": 0, "message": "no new transcripts"}

    # Load existing analyses
    existing = {}
    if KOL_INTEL_PATH.exists():
        try:
            existing = json.loads(KOL_INTEL_PATH.read_text())
        except Exception:
            existing = {}

    analyses = existing.get("analyses", [])
    processed_ids = _load_processed_ids()

    # Analyze each new transcript
    new_count = 0
    for t in transcripts:
        if t["video_id"] in processed_ids:
            continue

        logger.info(f"Analyzing: [{t['channel']}] {t['title'][:60]}...")
        result = extract_kol_sentiment(t)
        if result:
            analyses.append(result)
            processed_ids.add(t["video_id"])
            new_count += 1

        # Rate limit: 1 analysis per 2 seconds
        time.sleep(2)

    # Keep last 200 analyses (rolling window)
    analyses = sorted(analyses, key=lambda a: a.get("analyzed_at", ""), reverse=True)[:200]

    # Save updated intel
    intel_data = {
        "last_updated": datetime.now(timezone.utc).isoformat(),
        "total_analyses": len(analyses),
        "analyses": analyses,
    }
    KOL_INTEL_PATH.write_text(json.dumps(intel_data, indent=2))
    _save_processed_ids(processed_ids)

    # Build fresh digest
    digest = build_transcript_digest(hours=24)

    # Update sovereign context
    _update_sovereign_context(analyses, digest)

    logger.info(f"KOL intel updated: {new_count} new, {len(analyses)} total")
    return {
        "processed": new_count,
        "total": len(analyses),
        "digest": digest,
    }


def _update_sovereign_context(analyses: List[dict], digest: dict):
    """Push transcript intelligence into the sovereign context engine."""
    context_path = BASE_DIR / "data" / "sovereign_context" / "latest.json"
    if not context_path.exists():
        return

    try:
        ctx = json.loads(context_path.read_text())

        # Update KOL section with transcript intelligence
        scores = [a["sentiment_score"] for a in analyses[:20] if "sentiment_score" in a]
        topics = []
        for a in analyses[:20]:
            topics.extend(a.get("topics", []))

        # Deduplicate topics by frequency
        from collections import Counter
        topic_counts = Counter(t.lower() for t in topics)
        top_topics = [t for t, _ in topic_counts.most_common(5)]

        ctx["kol"] = {
            "sentiment_score": round(sum(scores) / len(scores)) if scores else 50,
            "top_topics": top_topics,
            "post_count_24h": len(analyses[:20]),
            "source": "transcript_intelligence",
            "dominant_sentiment": digest.get("dominant_sentiment", "neutral"),
            "creator_count": digest.get("creator_count", 0),
        }

        # Add transcript themes to narrative section
        if "narrative" not in ctx:
            ctx["narrative"] = {}
        ctx["narrative"]["kol_consensus"] = digest.get("summary", "")
        ctx["narrative"]["trending_kol_themes"] = [
            t["topic"] for t in digest.get("trending_themes", [])[:5]
        ]

        context_path.write_text(json.dumps(ctx, indent=2))
        logger.info("Sovereign context updated with transcript intelligence")

    except Exception as e:
        logger.error(f"Sovereign context update failed: {e}")


# ── API Helpers (called by routes) ───────────────────────────────────────────

def get_kol_sentiment() -> dict:
    """Return latest KOL sentiment data for API response."""
    if KOL_INTEL_PATH.exists():
        try:
            data = json.loads(KOL_INTEL_PATH.read_text())
            analyses = data.get("analyses", [])[:10]
            scores = [a["sentiment_score"] for a in analyses if "sentiment_score" in a]
            return {
                "avg_score": round(sum(scores) / len(scores), 1) if scores else 50,
                "creator_count": len(analyses),
                "last_updated": data.get("last_updated", ""),
                "creators": [
                    {
                        "channel": a["channel"],
                        "sentiment": a["sentiment"],
                        "score": a["sentiment_score"],
                        "thesis": a.get("main_thesis", ""),
                        "topics": a.get("topics", []),
                    }
                    for a in analyses
                ],
            }
        except Exception as e:
            logger.error(f"KOL sentiment read failed: {e}")

    return {"avg_score": 50, "creator_count": 0, "creators": [], "last_updated": ""}


def get_kol_themes() -> dict:
    """Return trending themes across creators for API response."""
    if KOL_DIGEST_PATH.exists():
        try:
            return json.loads(KOL_DIGEST_PATH.read_text())
        except Exception:
            pass
    return {"trending_themes": [], "creator_count": 0}


# ── CLI ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    )

    parser = argparse.ArgumentParser(description="Transcript Intelligence Pipeline")
    parser.add_argument("--hours", type=int, default=24, help="Hours of transcripts to process")
    parser.add_argument("--all", action="store_true", help="Process all transcripts")
    parser.add_argument("--digest", action="store_true", help="Build digest only (no new analysis)")
    args = parser.parse_args()

    if args.digest:
        digest = build_transcript_digest(hours=args.hours)
        print(json.dumps(digest, indent=2))
    elif args.all:
        # Process all — load everything, analyze unprocessed
        result = update_kol_intel()
        print(json.dumps(result, indent=2))
    else:
        result = update_kol_intel()
        print(json.dumps(result, indent=2))
