"""
MuseTalk Integration for Ultron
================================
Wrapper module for MuseTalk lip-sync inference on Ultron GPU server.
Deployed alongside api_server.py on the Ultron box.

This file gets SCP'd to ~/video_engine/musetalk_wrapper.py on Ultron.

Usage from api_server.py:
    from musetalk_wrapper import generate_avatar_video
    result = generate_avatar_video(audio_path, face_image_path, output_path)
"""
# NOTE: This is a reference/template file. The actual deployment file
# is generated by the deploy script and lives at:
#   ultron:~/video_engine/musetalk_wrapper.py
#
# See: scripts/deploy_musetalk.sh for installation steps.


MUSETALK_WRAPPER_CODE = '''
"""
MuseTalk Wrapper — Ultron GPU Server
Generates talking-head videos from face image + audio.
"""
import os
import sys
import json
import logging
import subprocess
from pathlib import Path

logger = logging.getLogger("MuseTalkWrapper")

MUSETALK_DIR = Path.home() / "MuseTalk"
WORK_DIR = Path.home() / "video_engine"
AVATARS_DIR = WORK_DIR / "output"

# Ensure avatars output exists
AVATARS_DIR.mkdir(parents=True, exist_ok=True)


def check_musetalk_available() -> bool:
    """Check if MuseTalk is installed and models are downloaded."""
    if not MUSETALK_DIR.exists():
        return False
    models_dir = MUSETALK_DIR / "models"
    # Check for essential model files
    required = [
        models_dir / "musetalk" / "pytorch_model.bin",
        models_dir / "sd-vae" / "diffusion_pytorch_model.bin",
        models_dir / "whisper" / "pytorch_model.bin",
    ]
    return all(f.exists() for f in required)


def generate_avatar_video(audio_path: str, face_image_path: str,
                           output_path: str, version: str = "v1.5") -> dict:
    """
    Generate a talking-head avatar video.

    Args:
        audio_path: Path to voiceover audio (.mp3 or .wav)
        face_image_path: Path to reference face image
        output_path: Where to save output video
        version: "v1.0" or "v1.5"

    Returns:
        {"status": "complete", "output": output_path, "duration": ..., "size_mb": ...}
        or {"status": "error", "error": "..."}
    """
    if not check_musetalk_available():
        return {"status": "error", "error": "MuseTalk not installed or models missing"}

    if not Path(audio_path).exists():
        return {"status": "error", "error": f"Audio not found: {audio_path}"}

    if not Path(face_image_path).exists():
        return {"status": "error", "error": f"Face image not found: {face_image_path}"}

    try:
        # Build MuseTalk inference command
        # MuseTalk uses its own inference script
        musetalk_venv = MUSETALK_DIR / "venv" / "bin" / "python3"

        cmd = [
            str(musetalk_venv),
            "-m", "scripts.inference",
            "--audio_path", str(audio_path),
            "--image_path", str(face_image_path),
            "--result_dir", str(Path(output_path).parent),
            "--output_name", str(Path(output_path).name),
        ]

        if version == "v1.5":
            cmd.extend(["--version", "v1.5"])

        logger.info(f"Running MuseTalk: {' '.join(cmd)}")

        result = subprocess.run(
            cmd,
            cwd=str(MUSETALK_DIR),
            capture_output=True,
            text=True,
            timeout=300,
            env={**os.environ, "CUDA_VISIBLE_DEVICES": "1"}  # Use GPU 1
        )

        if result.returncode != 0:
            logger.error(f"MuseTalk failed: {result.stderr[:500]}")
            return {"status": "error", "error": result.stderr[:500]}

        output_file = Path(output_path)
        if output_file.exists():
            size_mb = output_file.stat().st_size / (1024 * 1024)

            # Get duration via ffprobe
            duration = 0
            try:
                probe = subprocess.run(
                    ["ffprobe", "-v", "quiet", "-print_format", "json",
                     "-show_format", str(output_file)],
                    capture_output=True, text=True, timeout=10
                )
                if probe.returncode == 0:
                    fmt = json.loads(probe.stdout).get("format", {})
                    duration = float(fmt.get("duration", 0))
            except Exception:
                pass

            return {
                "status": "complete",
                "output": str(output_file),
                "size_mb": round(size_mb, 1),
                "duration": round(duration, 1)
            }
        else:
            return {"status": "error", "error": "Output file not created"}

    except subprocess.TimeoutExpired:
        return {"status": "error", "error": "MuseTalk timed out (300s)"}
    except Exception as e:
        return {"status": "error", "error": str(e)}
'''


# API endpoint code to add to api_server.py
AVATAR_ENDPOINT_CODE = '''
# --- Avatar Generation (MuseTalk) ---

@app.route("/generate_avatar", methods=["POST"])
@require_auth
def generate_avatar():
    """Generate a talking-head avatar video from face + audio."""
    data = request.json or {}
    audio_file = data.get("audio_file")
    face_image = data.get("face_image", "oracle_face.png")
    output_name = data.get("output_name")

    if not audio_file:
        return jsonify({"error": "audio_file required"}), 400

    # Resolve paths
    audio_path = DIRS["voiceovers"] / audio_file
    if not audio_path.exists():
        audio_path = DIRS["audio"] / audio_file
    if not audio_path.exists():
        return jsonify({"error": f"Audio file not found: {audio_file}"}), 404

    face_path = DIRS["assets"] / face_image
    if not face_path.exists():
        return jsonify({"error": f"Face image not found: {face_image}. Upload via /upload_asset first."}), 404

    if not output_name:
        output_name = f"avatar_{audio_file.replace('.mp3', '.mp4')}"

    output_path = DIRS["output"] / output_name
    job_id = create_job("avatar", {"audio": audio_file, "face": face_image, "output": output_name})
    update_job(job_id, status="processing")

    def run_avatar():
        try:
            from musetalk_wrapper import generate_avatar_video
            result = generate_avatar_video(str(audio_path), str(face_path), str(output_path))
            if result.get("status") == "complete":
                update_job(job_id, status="complete",
                           size_mb=result.get("size_mb", 0),
                           duration=result.get("duration", 0),
                           output_file=output_name)
            else:
                update_job(job_id, status="failed", error=result.get("error", "Unknown"))
        except Exception as e:
            update_job(job_id, status="failed", error=str(e))

    executor.submit(run_avatar)
    return jsonify({"job_id": job_id, "status": "processing", "output_name": output_name})
'''
