"""add push_subscription for web push whale alerts

Revision ID: 4638db2794ee
Revises: 6f4a0bc9a038
Create Date: 2026-02-12 04:49:19.522989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4638db2794ee'
down_revision = '6f4a0bc9a038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=True),
    sa.Column('auth', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index('idx_push_subscription_tier', ['tier'], unique=False)
        batch_op.create_index('idx_push_subscription_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscription_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscription_is_active'))
        batch_op.drop_index('idx_push_subscription_user_active')
        batch_op.drop_index('idx_push_subscription_tier')

    op.drop_table('push_subscription')
    # ### end Alembic commands ###
