"""pack0 add lead sentry_queue and partner click tracking fields

Revision ID: 6f4a0bc9a038
Revises: 03e6b7d4391f
Create Date: 2026-02-12 04:04:54.253285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4a0bc9a038'
down_revision = '03e6b7d4391f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('interest_level', sa.String(length=40), nullable=True),
    sa.Column('capacity_score', sa.Float(), nullable=True),
    sa.Column('btc_profile', sa.String(length=60), nullable=True),
    sa.Column('newsletter_opt_in', sa.Boolean(), nullable=True),
    sa.Column('funnel_stage', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index('idx_lead_created', ['created_at'], unique=False)
        batch_op.create_index('idx_lead_interest_capacity', ['interest_level', 'capacity_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_btc_profile'), ['btc_profile'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_capacity_score'), ['capacity_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_funnel_stage'), ['funnel_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_interest_level'), ['interest_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_newsletter_opt_in'), ['newsletter_opt_in'], unique=False)

    op.create_table('sentry_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platforms_json', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentry_queue', schema=None) as batch_op:
        batch_op.create_index('idx_sentry_queue_created', ['created_at'], unique=False)
        batch_op.create_index('idx_sentry_queue_status_schedule', ['status', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentry_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentry_queue_dry_run'), ['dry_run'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentry_queue_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentry_queue_status'), ['status'], unique=False)

    with op.batch_alter_table('partner_click', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('conversion_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('converted_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_partner_click_session_token', ['session_token'], unique=False)
        batch_op.create_index('idx_partner_click_slug_time', ['partner_slug', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_click_conversion_status'), ['conversion_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_click_session_token'), ['session_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_click', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_click_session_token'))
        batch_op.drop_index(batch_op.f('ix_partner_click_conversion_status'))
        batch_op.drop_index('idx_partner_click_slug_time')
        batch_op.drop_index('idx_partner_click_session_token')
        batch_op.drop_column('converted_at')
        batch_op.drop_column('conversion_status')
        batch_op.drop_column('session_token')

    with op.batch_alter_table('sentry_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentry_queue_status'))
        batch_op.drop_index(batch_op.f('ix_sentry_queue_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_sentry_queue_dry_run'))
        batch_op.drop_index(batch_op.f('ix_sentry_queue_created_at'))
        batch_op.drop_index('idx_sentry_queue_status_schedule')
        batch_op.drop_index('idx_sentry_queue_created')

    op.drop_table('sentry_queue')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_newsletter_opt_in'))
        batch_op.drop_index(batch_op.f('ix_lead_interest_level'))
        batch_op.drop_index(batch_op.f('ix_lead_funnel_stage'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))
        batch_op.drop_index(batch_op.f('ix_lead_created_at'))
        batch_op.drop_index(batch_op.f('ix_lead_capacity_score'))
        batch_op.drop_index(batch_op.f('ix_lead_btc_profile'))
        batch_op.drop_index('idx_lead_interest_capacity')
        batch_op.drop_index('idx_lead_created')

    op.drop_table('lead')
    # ### end Alembic commands ###
