"""Add screenshot_url to Article

Revision ID: fb645588212d
Revises: e6ae6d7fdbdd
Create Date: 2025-09-25 14:07:45.425191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb645588212d'
down_revision = 'e6ae6d7fdbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshot_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('screenshot_url')

    # ### end Alembic commands ###
